version: '3.8'
services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - voicevox
    
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
  # localstack:
  #   image: localstack/localstack
  #   ports:
  #     - "4566:4566" # LocalStackのデフォルトのエンドポイント
  #   environment:
  #     - SERVICES=s3,lambda,dynamodb # 必要なAWSサービスを指定
  #     - DEFAULT_REGION=us-east-1
  #     - EDGE_PORT=4566
  #   volumes:
  #     - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
