cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    hakuei:
      email: c1247183@st.kanazawa-it.ac.jp
      name: hakuei
      password: $2b$12$OqftIlYgmaqOgBOEkg/yqermsvV1q4YB0FkO7fmXoIByIiuOnhv7i
    test:
      email: test
      name: test
      password: $2b$12$DoPGfI0aDG/.KWWmY1Fio.Z95km88H78rr/XVaMX8SHv.EhoxumaC
preauthorized:
  emails:
  - melsby@gmail.com
