cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    TH:
      email: THTH@outllok.jp
      name: TH
      password: $2b$12$lRNBzIkBrfmWqbS2ehRJqufV9JpmYkl8LyYa4t48Zg3sBLop2XZNu
    hakuei:
      email: c1247183@st.kanazawa-it.ac.jp
      name: hakuei
      password: $2b$12$6cx.nI.3GOcyj.gIBA7UVOYUyqCgAqopo.oCEYEstjuV/SKPffxoa
    test:
      email: test
      name: test
      password: $2b$12$DoPGfI0aDG/.KWWmY1Fio.Z95km88H78rr/XVaMX8SHv.EhoxumaC
    test1:
      email: test1
      name: test1
      password: $2b$12$LkT5Cre1tm.NbVDDCE7qzuu/YjRpoXnxnNmBWxjCioiJhYTExY76i
    test3:
      email: test3
      name: test3
      password: $2b$12$JdW6pjCmfwoQkcQc63liQ.XDlv6Bhm0lyi5kiQBVyiql9Ybdpa5Ke
preauthorized:
  emails:
  - melsby@gmail.com
