name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # メインブランチへのプッシュでデプロイがトリガされます

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 依存関係が記載されたファイル
    - name: Deploy Streamlit to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # Herokuへのデプロイを行うAction
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "V-talk" # Herokuのアプリ名
        heroku_email: "nk3090@icloud.com" # Herokuアカウントのメールアドレス
